### ISSUE TITLE
Upgrade Guzzle to latest version (^7.0)

### ISSUE THREAD

**Issue by rayanlevert** [landrok/yousign-api#2]
Hello, I and a colleague have been using your library and it works great ;)

Would it be possible to upgrade Guzzle to its latest version (7.7.0 currently) in your requirements of composer ?

Thanks in advance ;)

**Comment by landrok** [comment]
Hi @levertr 

Yes, of course. Just done with 1.3.0 release + removed support for PHP 7.1

Thanks
